version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: circleci/php:7-apache-node-browsers
    steps:
      - run:
          name: Fix permissions
          command: 'sudo chown -R circleci:circleci /var/www' # https://discuss.circleci.com/t/permission-denied-during-checkout-phase/13665
      - checkout
      - run:
          name: Set PHP Timezone
          command: 'echo -e "[Date]\ndate.timezone = UTC" | sudo tee /usr/local/etc/php/php.ini > /dev/null'
      - run:
          name: Install Package Dependencies # Cacheable by checksum of lock
          command: 'composer install --no-dev --prefer-dist --no-interaction'
      - run:
          name: Create empty docs zip
          command: 'touch modmore-documentation.zip'
      - run:
          name: Building
          command: './build.sh'